### create new user
POST http://localhost:3000/user-api/users
Content-Type: application/json

{
    "username":"soujith",
    "email":"soujith@gmail.com",
    "password":"soujith",
    "gender":"MALE"
}

### user login
POST http://localhost:3000/user-api/auth
Content-Type: application/json

{
    "email":"soujith@gmail.com",
    "password":"newpass123"
}

### user logout
GET http://localhost:3000/user-api/logout

### user update by username
PUT http://localhost:3000/user-api/users
Content-Type: application/json

{
  "username": "soujithg",
  "email": "soujith@gmail.com",
  "password": "newpass123",
  "gender": "MALE"
}