### create new user
POST http://localhost:3000/user-api/users
Content-Type: application/json

{
    "username":"user1",
    "email":"user1@gmail.com",
    "password":"user1",
    "gender":"FEMALE"
}

### user login
POST http://localhost:3000/user-api/auth
Content-Type: application/json

{
    "email":"soujith@gmail.com",
    "password":"soujith"
}

### user logout
GET http://localhost:3000/user-api/logout

