### create new user
POST http://localhost:3000/user-api/users
Content-Type: application/json

{
    "username":"user2",
    "email":"user2@gmail.com",
    "password":"user2",
    "gender":"FEMALE"
}

### user login
POST http://localhost:3000/user-api/login
Content-Type: application/json

{
    "email":"soujith@gmail.com",
    "password":"soujith"
}

### user logout
GET http://localhost:3000/user-api/logout

### user update by username
PUT http://localhost:3000/user-api/users
Content-Type: application/json

{
  "username": "soujithg",
  "email": "soujith@gmail.com",
  "password": "newpass123",
  "gender": "MALE"
}

### get user by username
GET http://localhost:3000/user-api/find-user
Content-Type: application/json

{
    "username":"soujith"
}

### delete user
DELETE http://localhost:3000/user-api/delete-user
